### ISSUE TITLE
Why use ResLSTM for Offline Handwritten Chinese Text Recognition ?

### ISSUE THREAD

**Issue by ivoxx** [summerlvsong/Aggregation-Cross-Entropy#13]
Nice work!

I found this network architecture
_(126,576)Input − 8C3 − MP2 − 32C3 − MP2 − 128C3 − MP2−5∗256C3−MP2−512C3−512C3−MP2−512C2− 3 ∗ 512ResLSTM − 7357F C − Output_
in the paper for Handwritten Chinese Text Recognition.

Is it necessary for  Chinese Text Recognition ?

**Comment by DietDietDiet** [comment]
@ivoxx  Hi, I just have the same confusion, could you share your insights or comparing results? Thanks
