### ISSUE TITLE
Can you provide the data generator tool ?

### ISSUE THREAD

**Issue by lamhoangtung** [summerlvsong/Aggregation-Cross-Entropy#3]
Hi, thanks for the amazing works.

I was wondering that could you provide the tool that you guys have used to generate these toy dataset ?

Thanks you

**Comment by summerlvsong** [comment]
Hi, there are very few images (5000 traini/ 1000 test) in this toy dataset, therefore, we directly read the images without using tool like lmdb. Please refer to file "source/utils/data_loader.py".

**Comment by lamhoangtung** [comment]
@summerlvsong that’s not what I mean

How do you guys get the data from ? Did you guys generated all that images ?

**Comment by summerlvsong** [comment]
Yes, I misunderstood what you mean. The images are synthetic, we have not yet planned to open source code for data synthesis.

**Comment by lamhoangtung** [comment]
@summerlvsong Thanks
